---
name: CustomSound
version: 1.0.0
main: Mcbeany\CustomSound\CustomSound
api: 3.0.0
author: Mcbeany
description: Bringing custom sounds to the PocketMine server

commands:
  playsound:
    description: Plays a sound
    usage: /playsound <soundName:string> <target:string> [volume:float] [pitch:float]
  stopsound:
    description: Stops a sound
    usage: /stopsound <target:string> <soundName:string>
  reloadsound:
    description: Reload all sounds
permissions:
  customsound.commands:
    default: op
...
